security:
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    encoders:
       "FOS\UserBundle\Model\UserInterface": sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    firewalls:
        api:
            pattern:    ^/api
            stateless:  true
            anonymous:  true #false # can be omitted as its default value
            http_basic: ~

        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            logout:       true
            anonymous:    true

        secured_area:
            pattern: ^/api/auth/login
            security: false

    access_control:
        - { path: ^/api/(?!auth), roles: [ IS_AUTHENTICATED_FULLY ] }
        - { path: ^/login, roles: [IS_AUTHENTICATED_ANONYMOUSLY] }
        - { path: ^/register, roles: [IS_AUTHENTICATED_ANONYMOUSLY] }
        - { path: ^/resetting, roles: [IS_AUTHENTICATED_ANONYMOUSLY] }
